### ISSUE TITLE
Instance name

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#1143]
As a user I want to be able to name the instance.

There are 2 ways to name instance: [directly in the tree](https://github.com/webstudio-is/webstudio-builder/issues/222) and settings.
We are covering only naming from settings in this issue

## Todo
- [x] saving instance label from settings panel
- [x] using instance label in tree
- [x] using instance label in properties
- [x] outline info

![image](https://user-images.githubusercontent.com/52824/221908093-5f7f3f81-dcd5-4e79-a972-55aa20b03cde.png)
