### ISSUE TITLE
ChatGPT Integration

### ISSUE THREAD

**Issue by giuseppeg** [webstudio-is/webstudio-builder#1424]
We want to explore a ChatGPT integration in Webstudio. 

The ultimate goal would be to allow users to create pages or sections of them with prompts. On a high level technically this means getting instructions in natural language and generating structured content that is compatible with Webstudio's serialization format, resulting in the tool producing actual code.

At this stage it is hard to anticipate all the necessary steps to get to the final result therefore consider this issue as WIP and an evolving one or even a request for comments (RFC) - feel free to comment below.

Given that this is a greenfield project for now we'll organize in three phases: 

1. Validation and solution design
2. System design and API implementation 
3. Integration in the builder UI

Each phase will be broken down further in order to go in steps and reduce risk (feasibility/time/resources).

## Phase 1 - Validation

The bulk of the work / complexity of this project is all about prompt engineering. We need to figure out a precise way of crafting prompts so that we provide all the information necessary to generate valid structured content. This is a non-trivial task. 

While initially I will be playing with the free ChatGPT UI, soon I might need an API key:

- [ ] @kof to provide an OpenAI API key if necessary

In this phase we want to:

- [ ] Explore the current capabilities of ChatGPT (quality of output and the like). 

This is prompting engineering work that will go towards trying to understand if the tool can fulfill requests such as creating a landing page or parts of it and then generate precise answers in a format that we expect (HTML or similar). 

A non-comprehensive list of things to try (please add suggestions):

- [ ] Explore current understanding of HTML/CSS and quality of the output 
- [ ] Ask GPT to produce an [hast](https://github.com/syntax-tree/hast) (HTML AST) might be an idea worth trying as it might already know about it
- [ ] Try the same as above but with React components?
- [ ] Using Webstudio's components' signatures/metadata try to craft an example for GPT for the `Box` component - this will go along with the user prompt 
- [ ] Explore nesting

Questions:

- [ ] It'd be great if you could provide pointers to Webstudio's specific bits that I might need to know about: i.e. components, metadata, public type definitions and basic architectural information like: how is CSS handled. Of course I can figure all this out myself but probably we'll save a decent amount of time if I get a tl;dr from you.

--- 

- [ ] Research current approaches (if any) to solve similar problems - it is always worth researching existing academia or public work/solutions 

---

- [ ] Work towards creating a standard prompt format to define a Webstudio component

We need to figure out the minimum amount of information to create a quality emebedding for the component. [Here](https://www.youtube.com/watch?v=Ue7M826xj5M)'s a decent and easy to grasp explanation of what embeddings are.

[Embeddings](https://platform.openai.com/docs/guides/embeddings) measure the relatedness of text strings. The idea here is that:

1. we create an archive of embeddings that describe the whole Webstudio components library and save them on a vector db
4. when a user prompt comes in we generate an embedding for that prompt
5. fetch the top N related Webstudio embeddings from the vector db
6. construct the prompt with user request + examples (top N related embeddings' metadata)

In the beginning as we explore an MVP we'd skip the vector db and store to file. Once validated we should move to a vector db right away.

For this part we should use (and perhaps enrich) the [Webstudio components' metadata](https://github.com/webstudio-is/webstudio-builder/blob/1ecea88ddb1fadd956ff670d850b1690247c94c6/packages/react-sdk/src/components/box.ws.ts#L35) and possibly the [generated types](https://github.com/webstudio-is/webstudio-builder/blob/1ecea88ddb1fadd956ff670d850b1690247c94c6/packages/react-sdk/src/components/__generated__/box.props.ts). 

---

- [ ] Work towards defining a structured text format (a schema) from existing Webstudio information to feed to ChatGPT. 

This should educate ChatGPT about the Webstudio's structured content format. 

user request + examples is for **what** we want
the schema definition is for **how** we want it

---

## Phase 2 - System design and API implementation 

**IF Phase 1 is successful/works** then we'll have to make more concrete design decisions about:

- [ ] a solution that fits the current token limits: I think it is 4k tokens. With GPT4 the limit is 8k to 32k tokens.
- [ ] defining final spec for embeddings generation and structured content
- [ ] generating and storing embeddings upon changes and manually
- [ ] operational things like rate limits, hosting requirements and issues that might arise due to OpenAI's API usage
- [ ] storing accepted GPT answers for future context and to improve prompts. Carefully consider all the privacy implications of this (maybe per-user storage and not shared is the most safe option).
- [ ] product in general

- [ ] Implement solution in code based on decisions above - this would be an API endpoint that can be used headlessly

---

## Phase 3 - Execution

- [ ] Integrate the API above in the builder UI/app

**Comment by ggurgone** [comment]
Closing in favor of https://github.com/webstudio-is/webstudio-builder/issues/1450
