### ISSUE TITLE
Vimeo Component

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#1688]
## Research

1. Both youtube and vimeo add a shitload of scripts to the page.  If you just include their embed iframe as-is you site will be much slower guaranteed
1. Youtube has a nocookie mode  and yet as soon as you add a youtube video it adds a shitload of tracking. They just use local storage instead https://stackoverflow.com/questions/61887699/gdpr-youtube-nocookie-embedded-urls-need-visitors-permission
1. To load any of them efficiently I used an Image component with a play button on it. Once it is clicked I render the video in autoplay mode so that user doesn't have to click twice.
1. There are a bunch of other options to customize the players that would require user to read their documentation
1. Vimeo is apparently GDPR compliant, so it doesn't need a banner.
1. Background mode is possible

    - All player toggles and elements will be turned off (including the play/pause button!) 
    - The video will automatically loop.
    - The video will be set to autoplay.
    - The video will be muted.

    But will insert all scripts for the video player on the page, so again we need a "lazy" option to avoid affecting page speed

1. If somebody uses Youtube video, they need a gdpr consent dialog.

1. We could have a consent dialog component as a component user can add to the page with built-in functionality
we could have it added by the user inside video component so that it shows up first time only when a user clicks on the image to play a video, since before that, there is no tracking (if we do it the way I describe) and hence no need for consent.

Generally I think local-specific consent for something when it's actually used is better for many many cases, especially with youtube.

Lite versions for embedding: 
- https://github.com/slightlyoff/lite-vimeo/
- https://github.com/paulirish/lite-youtube-embed/

Both do: 
- show image, only load player on click
- on hover preconnect 

Vimeo embed API https://developer.vimeo.com/player/sdk/basics
Youtube embed API https://developers.google.com/youtube/iframe_api_reference

## Todo Vimeo
- [x] Vimeo component
- [x] Parse vimeo url to get the video id required for js api
- [x] Create a default placeholder tree that is visible initially and can be changed by the user
- [x] Handle click on the instance root to load the player and autoplay
- [x] Remove children once player is loaded and starts playing to avoid jumps
- [x] Expose supported settings over properties 
- [x] Preconnect ssl on hover
- [x] Handle url parsing errors
- [x] render vimeo preview image
- [x] color control -  depends on https://github.com/webstudio-is/webstudio-builder/issues/1154
- [x] base64 image source should show control just like asset - https://github.com/webstudio-is/webstudio-builder/issues/1721
- [x] url prop type
- [x] fix vimeo icon color
- [x] check accessibility
- [x] final design of the default preview
- [x] simplify  Portrait, Title, and Byline 
- [x] add loading indication after initialization click

**Comment by taylornowotny** [comment]
Excellent work @darindimitroff ! In the future I will start some designs with a document like this as it really helps organize the many decisions that need to be made around a new feature.

I only have one comment about the feature. Let's make sure that controls like "Mute", "Autoplay", and "Show video controls" are included as these are strongly relevant to accessibility. I don't want to cut these for time.

There's dozens of Webflow support posts from people missing these features or struggling to make their video work the way they want it to. IIRC the creation of the Background Video element had something to do with the lack of accessible controls on the main video element ? Correct me if I'm wrong

+ are there any other accessibility considerations for the video component? Captions?

**Comment by kof** [comment]
@darindimitroff @taylornowotny I found vimeo itself is using this initial design when video is first rendered but is not playing. Seems like we should copy that 1:1, except the image itself. I mean the Play button design.


<img width="1211" alt="Screenshot 2023-06-04 at 13 35 41" src="https://github.com/webstudio-is/webstudio-builder/assets/52824/87f5c1b4-beeb-4486-8b86-d8bcf57664ae">


<img width="1210" alt="Screenshot 2023-06-04 at 13 35 33" src="https://github.com/webstudio-is/webstudio-builder/assets/52824/c56e78b6-30e0-4929-a974-1dddd97f0192">

**Comment by kof** [comment]
Closing, tbc in https://github.com/webstudio-is/webstudio-builder/issues/1747

**Comment by Erudition** [comment]
> but I don't see any real reasons to do a separate Background video component.
Not a component, but simply setting the video as a css `background` source, no? Rather than messing with absolute positioning and losing the handy `background` styles like position, size, fit, attachment, etc.
This is something I really love from the FLO tool Elementor

**Comment by kof** [comment]
Unfortunately this is not how it works in the browser, the only way to get video render as a background one is using absolute position and positioning it behind the front layer
