### ISSUE TITLE
New Tooltips Component!

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio-builder#1730]
The long awaited tooltips are here!

Please read the docs very carefully, share any feedback, and ask me any questions.

<img width="1404" alt="Screenshot 2023-06-07 at 3 13 01 PM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/d9b97969-6696-4cd4-a125-8db96d0f0ba9">

Figma: https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=5025-52255

## Todo

- [x] cmd+click shortcut should reset any property
- [x] reset button
- [x] css preview
- [x] value comes from badges
- [ ] jump button for style source that can lead user to breakpoint, instance, token
- [ ] link to mdn for css preview
- [x] short descriptions for all properties (gpt?)

**Comment by kof** [comment]
Closing this one, tbc in https://github.com/webstudio-is/webstudio-builder/issues/1798
