### ISSUE TITLE
Show first templates in dashboard

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#2134]
To let users start from a template instead of a blank canvas, we need to add some starter templates now.

## Todo
- [x] Hardcoded list of projects that can be cloned
- [x] Hardcoded permissions for that list to allow cloning for everyone
- [x] Section "Templates" under Projects
- [x] Items are the same but no menu
- [x] Click should open Dialog (same as rename dialog)
- [x] Click "Create" creates a clone with that name and opens in builder

**Comment by taylornowotny** [comment]
Great 👍 

If you want a preview of this UI, please ask @markxtang since he designed the Dashboard. It should all be possible with existing UI so nothing new is needed, just a repurposing of the current "Projects" section design with a new title and no button.

@markxtang can you confirm which templates are ready and please make a cover image for each one? The cover image would preferably be a small screenshot of the top of the home page, to give the user an idea of what the site looks like before they open it.
