### ISSUE TITLE
Rename Designer to Builder

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#791]
As per the discussion on discord, we want to rename Designer to Builder, because it is confusing between a person and an app having the same name and since the main user of Builder UI is a Designer (person), we are better off having different names.

## Todo
- [x] rename repository
- [x] rename URL in the router
- [x] rename all usages in code
- [x] rename area:designer label
- [x] search for usages in documentation
- [x] change Vercel configuration (baseDir) to `apps/builder`
- [x] rename `DESIGNER_HOST` env variable to `BUILDER_HOST` in Vercel

**Comment by kof** [comment]
I think this is done?
