### ISSUE TITLE
New Landing Site

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio-builder#880]
## Todo

- [x] implement mvp design
- [x] add blog
- [x] implement first article
- [x] design articles list
- [x] implement articles list
- [x] implement made in webstudio badge
- [x] implement the pricing page
- [x] connect the project to webstudio.is domain

**Comment by kof** [comment]
closing this as done
